name: Build and Deploy Jekyll

on:
  push:
    branches:
      - main   # or your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2 # matches GitHub Pages
        bundler-cache: true

    - name: Install Jekyll & dependencies
      run: |
        gem install jekyll bundler github-pages

    - name: Build Jekyll Site
      run: jekyll build --destination ./_site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        publish_branch: gh-pages
